may_blog/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
import uuid
from werkzeug.security import generate_password_hash, check_password_hash
import secrets
from flask_login import UserMixin, LoginManager

db = SQLAlchemy()
login_manager = LoginManager()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key=True)
    username = db.Column(db.String(150), nullable=False, unique=True)
    email = db.Column(db.String(150), nullable=False, unique=True)
    password = db.Column(db.String(256), nullable=False)
    post = db.relationship('Post', backref='author', lazy=True)

    def __init__(self, username, email, password, id= ''):
        self.id = self.set_id()
        self.username = username
        self.email = email
        self.password = self.set_password(password)

    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash
    
    def __repr__(self):
        return f'{self.username} has been created with {self.email}'

class Post(db.Model):
    id = db.Column(db.String, primary_key=True)
    title = db.Column(db.String(200))
    content = db.Column(db.String(300))
    date_created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.String, db.ForeignKey('user.id'), nullable=False)

    def __init__(self, title, content, user_id, id = ''):
        self.id = self.set_id()
        self.title = title
        self.content = content
        self.user_id = user_id

    def set_id(self):
        return str(uuid.uuid4())

    def __repr__(self):
        return f'The title of the post is {self.title} \n and the content is {self.content}.'

may_blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email
from flask_login import UserMixin


class UserInfoForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField()

class UserLoginForm(FlaskForm,UserMixin):
    # email, password, submit button
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit_button = SubmitField()

class BlogPostForm(FlaskForm):
    title = TextAreaField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField()

may_blog/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from flask_migrate import Migrate
from may_blog.models import db as root_db, login_manager


app = Flask(__name__)

app.config.from_object(Config)

app.register_blueprint(site)
app.register_blueprint(auth)

root_db.init_app(app)
migrate = Migrate(app, root_db)

login_manager.init_app(app)

from may_blog import models

may_blog/authentication/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from may_blog.forms import UserLoginForm, UserInfoForm
from may_blog.models import User, check_password_hash, db

from flask_login import login_user, logout_user, current_user, login_required


auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserInfoForm()

    if request.method == 'POST' and form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        email = form.email.data
        print("\n",username, password, email)
        
        user = User(username, email, password)
        db.session.add(user)
        db.session.commit()

        flash(f'You have successfully created a user account {email}', 'user-created')
        return redirect(url_for('site.home'))

    return render_template('signup.html', form = form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    if request.method =='POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)
        
        logged_user = User.query.filter(User.email == email).first()

        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash('You were successfully logged in: Via Email/Password', 'auth-success')
            return redirect(url_for('site.home'))
        else:
            flash('Your Email/Password is incorrect', 'auth-failed')
            return redirect(url_for('auth.signin'))

    return render_template('signin.html', form = form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

may_blog/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from may_blog.models import Post, db
from may_blog.forms import BlogPostForm

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    posts = Post.query.all()
    return render_template('index.html', posts=posts)

@site.route('/profile')
def profile():
    return render_template('profile.html')

@site.route('/createposts', methods=['GET','POST'])
@login_required
def createposts():
    form = BlogPostForm()
    if request.method == 'POST' and form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        user_id = current_user
        print('\n', title, content)
        post = Post(title, content, user_id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('site.createposts'))
    return render_template('createposts.html', form=form)

may_blog/templates/auth_login.html
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <fieldset>
                {{ form.email.label }}
                {{ form.email(class="form-control", placeholder="Email") }}
            </fieldset>
            <fieldset>
                {{ form.password.label }}
                {{ form.password(class="form-control", placeholder="Password") }}
            </fieldset>
            {{ form.submit_button(class="btn btn-primary") }}
        </div>
    </form>

may_blog/templates/auth_register.html
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset>
            {{ form.username.label }}
            {{ form.username(class="form-control", placeholder="Username") }}
        </fieldset>
        <fieldset>
            {{ form.email.label }}
            {{ form.email(class="form-control", placeholder="Email") }}
        </fieldset>
        <fieldset>
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder="Password") }}
        </fieldset>
        {{ form.submit(class="btn btn-success") }}
    </div>
</form>

may_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<!--The following 2 script tags are for our Flash messages.. this will NOT be an error-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
      $(".close").click(function(){
        $(".alert").hide(1000);
      });
    });
    </script>
    <!--Again - the previous 2 script tags are not an error. This is JavaScript shorthand to hide an 'alert' class when we click a 'close' class-->
<title>May Operators Blog</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('site.home') }}">May Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('site.home') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('site.createposts') }}">Add a Blog Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.signin') }}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.signup') }}">Register Account</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    {% block content %}
    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>